
name: Deploy API
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ClinicalCoding.Api/**'
      - 'ClinicalCoding.Domain/**'
      - 'ClinicalCoding.Infrastructure/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish
        run: dotnet publish ClinicalCoding.Api/ClinicalCoding.Api.csproj -c Release -o ./publish
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
